spring:
  profiles:
    active: dev
  application:
    name: demo
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:3306/datn
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
  data:
    redis:
      repositories:
        enabled: false
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
      type: redis
      redis:
        time-to-live: 1800000 # TTL 30 phút (ms)
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  mail:
    host: smtp.gmail.com
    port: 587
    username: tienolympia2020@gmail.com
    password: blgrmrhmzuososbs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  web:
    resources:
      static-locations: classpath:/static/, file:/var/app/static/
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

jwt:
  secret: ${JWT_SECRET:defaultSecretKeyForDevelopmentOnlyPleaseChangeInProduction123456789}
  access_ttl: 60
  refresh_ttl: 43200

app:
  static:
    upload-dir: /home/tien/Pictures/phongkham
logging:
  level:
    org.springframework.security: ${LOG_LEVEL_SECURITY:DEBUG}

springdoc:
  swagger-ui:
    path: /docs


r2:
#  account_id: 348b437eb42cb30d353b601b82e8a9a9               # ví dụ: abcdef1234567890abcdef1234567890
  bucket: phongkham
  access_key: d927fe84a0c82ed69fe9d5a914689a2c
  secret_key: 03d4db385f4ae750d969964ddbb09d130cb647dfd170daad64ee58097a0cce03
  endpoint: https://348b437eb42cb30d353b601b82e8a9a9.r2.cloudflarestorage.com/phongkham
